export const LOGGING_IN = "USER_LOGGING_IN";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";

export const SET_LOADING_POPULAR = "SET_LOADING_POPULAR";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const LOAD_MORE_POPULAR_MOVIES = "LOAD_MORE_POPULAR_MOVIES";
